// <auto-generated />
namespace br.com.Chronos.AcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AtualizarEscritorio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtualizarEscritorio));
        
        string IMigrationMetadata.Id
        {
            get { return "201510271620148_AtualizarEscritorio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
