//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.Chronos.Idioma.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("br.com.Chronos.Idioma.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros.
        /// </summary>
        public static string Cadastros {
            get {
                return ResourceManager.GetString("Cadastros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Conclusão.
        /// </summary>
        public static string DataConclusaoOS {
            get {
                return ResourceManager.GetString("DataConclusaoOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação .
        /// </summary>
        public static string DataCriacao {
            get {
                return ResourceManager.GetString("DataCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Vencimento.
        /// </summary>
        public static string DataVencimentoOS {
            get {
                return ResourceManager.GetString("DataVencimentoOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string DescricaoOS {
            get {
                return ResourceManager.GetString("DescricaoOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        public static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        public static string Eventos {
            get {
                return ResourceManager.GetString("Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string IdSetor {
            get {
                return ResourceManager.GetString("IdSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string NivelDaOS {
            get {
                return ResourceManager.GetString("NivelDaOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Documento.
        /// </summary>
        public static string NomeDocumento {
            get {
                return ResourceManager.GetString("NomeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto Chronos.
        /// </summary>
        public static string NomeProjeto {
            get {
                return ResourceManager.GetString("NomeProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Reduzido.
        /// </summary>
        public static string NomeReduzido {
            get {
                return ResourceManager.GetString("NomeReduzido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. OS.
        /// </summary>
        public static string NumeroOS {
            get {
                return ResourceManager.GetString("NumeroOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string ObservacaoOS {
            get {
                return ResourceManager.GetString("ObservacaoOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Exemplo.
        /// </summary>
        public static string ReferenciaExemplo {
            get {
                return ResourceManager.GetString("ReferenciaExemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resp. Conclusão.
        /// </summary>
        public static string ResponsavelConclusaoOS {
            get {
                return ResourceManager.GetString("ResponsavelConclusaoOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resp. Criação.
        /// </summary>
        public static string ResponsavelCriacao {
            get {
                return ResourceManager.GetString("ResponsavelCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor.
        /// </summary>
        public static string Setor {
            get {
                return ResourceManager.GetString("Setor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
